# Generated by Django 4.2.10 on 2024-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_role_user_favorites_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(blank=True, choices=[(1, "Member"), (2, "President")], default=1, null=True),
        ),
    ]
