# Generated by Django 4.2.10 on 2024-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="coupons",
            field=models.ManyToManyField(blank=True, related_name="products", to="products.coupon"),
        ),
        migrations.AlterField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(blank=True, related_name="products", to="products.supplier"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tags", to="products.tag"),
        ),
    ]
