# Generated by Django 4.2.10 on 2024-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_cartitem_customer_cartitem_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.RenameField(
            model_name="address",
            old_name="street",
            new_name="line1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="address",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="address",
            name="line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="pincode",
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.IntegerField(
                choices=[(1, "Home"), (2, "Work"), (3, "Other"), (4, "Billing Address"), (5, "Shipping Address")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
