# Generated by Django 4.2.10 on 2024-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_remove_address_country_remove_address_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.IntegerField(choices=[(1, "Home"), (2, "Work"), (3, "Other")]),
        ),
    ]
