# Generated by Django 4.2.10 on 2024-05-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_address_address_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
    ]
