# Generated by Django 4.2.10 on 2024-05-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("razorpay_order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("razorpay_signature_id", models.CharField(blank=True, max_length=128, null=True)),
                ("razorpay_invoice_id", models.CharField(blank=True, max_length=100, null=True)),
                ("invoice_file", models.FileField(blank=True, null=True, upload_to="invoices/")),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Confirmed"), (3, "Shipped"), (4, "Delivered"), (5, "Canceled")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_orders",
                        to="customers.address",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="products.coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productvariant"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="product_variants",
            field=models.ManyToManyField(through="orders.OrderItem", to="products.productvariant"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_orders",
                to="customers.address",
            ),
        ),
    ]
