# Generated by Django 4.2.10 on 2024-03-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_id",
            new_name="razorpay_order_id",
        ),
    ]
