# Generated by Django 4.2.10 on 2024-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_payment_id_order_razorpay_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_invoice_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
