# Generated by Django 4.2.10 on 2024-02-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("tracking_url_template", models.URLField(blank=True, max_length=1024, null=True)),
                ("api_endpoint", models.URLField(blank=True, max_length=1024, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tracking_number", models.CharField(blank=True, max_length=255, null=True)),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.IntegerField(choices=[(1, "Pending"), (2, "Shipped"), (3, "Delivered")], default=1)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shipment", to="orders.order"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shippings.shippingprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "In Transit"), (2, "Out for Delivery"), (3, "Delivered")], default=1
                    ),
                ),
                ("status_date", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_statuses",
                        to="shippings.shipment",
                    ),
                ),
            ],
        ),
    ]
