# Generated by Django 4.2.10 on 2024-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PincodeAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pincode", models.CharField(max_length=6, unique=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pincode", models.CharField(max_length=6, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_delivery_days", models.IntegerField()),
            ],
        ),
    ]
